<a href="https://colab.research.google.com/github/r-autowired/AIMLWorks/blob/main/Notes/PyTorch/HandsOn_PyTorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('Hello Im excited to learn PyTorch')

Hello Im excited to learn PyTorch


In [3]:
!nvidia-smi


Wed Jun 18 02:00:27 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
print(torch.__version__)

2.6.0+cu124


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(pd.__version__)
print(np.__version__)


2.2.2
2.0.2


##Intro to Tensors



### Creating Tensors

In [6]:
## scalar
scalar = torch.tensor(7)
scalar

##? PyTorch tensors are created using torch.Tensor()

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
## Get tensor back as python int
scalar.item()

7

In [9]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
from re import M
## MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
## Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random Tensors
- WHy this important is bcos the neural networks start with random data and adjust those randome numbers to better represent the data

 - start with random numbers --> look at the data --> update the random numbers --> look at the data --> update the random numbers ....

In [20]:
## Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1666, 0.0077, 0.2599, 0.3710],
        [0.4404, 0.6631, 0.1996, 0.8661],
        [0.7228, 0.7442, 0.2255, 0.2883]])

In [21]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [22]:
random_tensor1 = torch.rand(1,3,4)
random_tensor1

tensor([[[0.6064, 0.0490, 0.7000, 0.3295],
         [0.5212, 0.7138, 0.5784, 0.0767],
         [0.8751, 0.3454, 0.8111, 0.6115]]])

In [23]:
random_tensor1.ndim, random_tensor1.shape

(3, torch.Size([1, 3, 4]))

In [24]:
random_tensor_image = torch.rand(size=(224,224,3))
random_tensor_image.shape, random_tensor_image.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create a tensor for all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

### Range in Tensors

In [29]:
# Creating a range
torch.arange(0,10), torch.arange(start=1, end=11), torch.arange(start=1, end=11, step=2)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 3, 5, 7, 9]))

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=torch.arange(0,10)) ## is a variable in the input
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
- 3 big erros with pytorch and deep learning
  - Tensors not right datatype (float16 vs float32)
  - Tensors not right shape (1,10) vs (1,11)
  - Tensors not right on DEVICE - CPU vs CUDA

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on - CPU or CUDA
                               requires_grad=False) # Whether or not to track the gradients with this Tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_32_tensor * float_16_tensor
#

tensor([ 9., 36., 81.])

In [34]:
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([3]), device(type='cpu'))

### Manipulating Tensors
 - Addition
 - Subtraction
 - Multiplication
 - Division
 - Matrix Multiplication
  - **inner dimension** should match for multiplication
  - **outer dimmension** will be the shape of the final output
  

In [35]:
# Creat a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
# Try out pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
# Matrix Multiplication
matmul_val = torch.matmul(tensor, tensor) ## Matmul is fater than doing it in for loop iterating one item after another
matmul_val
## This is an one dimension tensor array and dot(.) product is used for multiplication and hence 14

tensor(14)

In [39]:
matmul_val.item()

14

In [40]:
tensor1 = torch.tensor([[1],
                        [2],
                        [3]])

In [41]:
%%time
val = torch.matmul(tensor, tensor1)
val
## This is the real matrix multiplication

CPU times: user 286 µs, sys: 48 µs, total: 334 µs
Wall time: 1.24 ms


tensor([14])

In [42]:
%tensorflow_version

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [43]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10,9],
                         [8,11,12]])
torch.mm(tensor_A, tensor_B) ## torch.mm is the same as torch.matmul (it's an alias for matmul)

tensor([[ 23,  32,  33],
        [ 53,  74,  75],
        [ 83, 116, 117]])

- In order fix this i manually made change to tensor_B matrix but we could use **Transpose**

In [44]:
tensor_c = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_d = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_c, tensor_d.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation (min, max, mean, sum, etc...)

In [45]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
x.dtype

torch.int64

In [47]:
#min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [48]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [49]:
#mean
torch.mean(x.type(torch.float32)),  x.type(torch.float32).mean()
## if we do torch.mean(x) it will throw error as the dtype of x is not float32. x.dtype == int64

(tensor(45.), tensor(45.))

In [50]:
# Finding positional values on aggregation
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

### Reshaping, stacking, squeezing, and unsqueezing tensors
 - Reshaping - reshapes an input tensor to a defined shape
 - View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
 - Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
 - Squeez -  removes all '1' dimensions from a tensor
 - Unsqueez - add a '1' dimension to a target tensor
 - Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [51]:
#
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension
x_reshaped = x.reshape(1,9) ## x.reshape(9,1) will also work bcos the given x is of 1 dimension (1,9) and can be changed to (9,1)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
x_reshaped1 = x.reshape(3,3) ##  the size of given x is 9 and any matrix with a shape that can match with given x shape will work !!!
x_reshaped1, x_reshaped1.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [54]:
# change the view
x_view = x.view(1,9)
x_view, x_view.shape  ## Changing x_view (view) changes x - why ? bcos - tensor view shares the same memory of the original data given

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
x_view[:, 0] = 5
x_view, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
# Stack
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked
#

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
# Stack
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked
#

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [59]:
x, x.shape,  x_reshaped, x_reshaped.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [60]:
# Squeez
x_squeezed = torch.squeeze(x_reshaped)
x_squeezed, x_squeezed.shape ,x_reshaped, x_reshaped.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

- squeez just removes multi dimensional matrix and merge into single dimension

In [61]:
# Unsqueez
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# Unsqueez
x_unsqueezed2 = torch.unsqueeze(x_squeezed, dim=1)
x_unsqueezed2, x_unsqueezed2.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
# Permute - rearranges the target matrix in specified order
x_original = torch.rand(size=(2,3,4))
x_original.shape, "<-->", x_original.ndim, "<-->" ,x_original.size(), "<-->", x_original

(torch.Size([2, 3, 4]),
 '<-->',
 3,
 '<-->',
 torch.Size([2, 3, 4]),
 '<-->',
 tensor([[[0.0075, 0.5062, 0.8786, 0.5312],
          [0.7871, 0.6985, 0.4987, 0.0214],
          [0.9838, 0.8252, 0.0538, 0.0718]],
 
         [[0.2193, 0.0427, 0.2501, 0.9984],
          [0.9661, 0.8466, 0.9053, 0.8598],
          [0.5143, 0.1426, 0.2789, 0.5905]]]))

In [64]:
x_permuted = torch.permute(x_original, (2,0,1)) ## Expected range is -3 to 2 ?? 3 dim take number from [-3, -2, -1, 0, 1, 2]
x_permuted.shape, "<-->", x_permuted.ndim, "<-->" ,x_permuted.size(), "<-->", x_permuted

(torch.Size([4, 2, 3]),
 '<-->',
 3,
 '<-->',
 torch.Size([4, 2, 3]),
 '<-->',
 tensor([[[0.0075, 0.7871, 0.9838],
          [0.2193, 0.9661, 0.5143]],
 
         [[0.5062, 0.6985, 0.8252],
          [0.0427, 0.8466, 0.1426]],
 
         [[0.8786, 0.4987, 0.0538],
          [0.2501, 0.9053, 0.2789]],
 
         [[0.5312, 0.0214, 0.0718],
          [0.9984, 0.8598, 0.5905]]]))

### Indexing (selecting data from tensors)
- Indexing is pytorch is similar to indexing with NumPy

In [65]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
x[0][0]

tensor([1, 2, 3])

In [68]:
x[0, 0]

tensor([1, 2, 3])

In [69]:
x[0][0][0]

tensor(1)

In [70]:
x[0, 0 ,0]

tensor(1)

In [71]:
# Get all values of 0th and 1st dimensions but only index 1of 2nd dimension
x[:, : , 1]  ## Take column value

tensor([[2, 5, 8]])

In [72]:
x[:, 1, 1] ## Below we get tensor within []  brackets but x[0,1,1] will output tensor(5)
## This gives back the scalar value but the one below gives the slice of the tensor

tensor([5])

- Pytorch tensors and NumPy
  - Data in NumPy want in PyTorch tensor --> torch.from_numpy(ndarray)
  - PyTorch tensor --> NumPy --> torch.Tensor.numpy()

In [75]:
#
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  ##.type(torch.float32) --> you can change the type to float32 and tensor dtype wil also change to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

-  dtype=torch.float64 ? why ?
 - array.dtype = float64
 - tensor.dtype = float64
 - above array dtype is float64 and hence tensor dtype as well
 - But Tensor is always float32
 - But - torch.arange(1.0, 8.0) produces float32

In [76]:
# If i change array tensor will not change
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Tensor to NumPy
tensor1 = torch.ones(4)
tensor1, tensor1.dtype

(tensor([1., 1., 1., 1.]), torch.float32)

In [81]:
numpy_array = tensor1.numpy()
print(numpy_array, numpy_array.dtype)

[1. 1. 1. 1.] float32


### Reproducibility (trying to take random out of random)
- To reduce randomness in neural and PyTorch comes the concept of **random seed**

- Essentially what the random seed does is "flavour" the randomness

In [85]:
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.4162, 0.2111, 0.6220, 0.1321],
        [0.5107, 0.9190, 0.9980, 0.6581],
        [0.7114, 0.6324, 0.4498, 0.8303]])
tensor([[0.7747, 0.5078, 0.5643, 0.6447],
        [0.8291, 0.4062, 0.7391, 0.0548],
        [0.5034, 0.5113, 0.8728, 0.7609]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [87]:
# Set Random Seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensors and PyTorch objects on GPUs and making it faster computations


In [88]:
# Getting GPU
#1.
!nvidia-smi

Wed Jun 18 02:28:20 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [89]:
## Get to see GPU with PyTorch
torch.cuda.is_available()

True

In [90]:
## Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [91]:
## Count number of devices
torch.cuda.device_count()

1

- https://docs.pytorch.org/docs/stable/notes/cuda.html

In [92]:
## Putting tensors and models on the GPU
#
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device) ## Its not GPU and its CPU

tensor([1, 2, 3]) cpu


In [99]:
tensor.numpy()

array([1, 2, 3])

In [100]:
tensor_on_gpu = tensor.to(device) #tensor_back_on_cpu.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [101]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [97]:
## Moving tensors back to cpu
tensor_on_gpu.to('cpu')


tensor([1, 2, 3])

In [104]:
tensor_on_gpu.cpu().numpy(), tensor_on_gpu

(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

In [102]:
## Moving tensors back to cpu
tensor_on_gpu.cpu().detach().numpy()

array([1, 2, 3])